[package]
name = "codegen"
version = "0.1.0"
edition = "2021"

[dependencies]
quote = "1.0.38"
syn = { version = "2.0.96", features = ["full", "extra-traits"] }
ungrammar = "1.16.1"
bord-sqlite3-parser = { path = "../sqlite3-parser" }