[package]
name = "yukon-server"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.86"
crossbeam = "0.8.4"
hashbrown = "0.14.5"
line-index = "0.1.1"
lsp-server = "0.7.6"
lsp-types = "0.94.0"
serde = "1.0.203"
serde_json.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
yukon-sqlite3-parser = { path = "../sqlite3-parser" }
