[package]
name = "yukon-sqlite3-parser"
version = "0.1.0"
edition = "2021"

[dependencies]
ahash.workspace = true
enumset = "1.1.3"
smol_str.workspace = true

[dev-dependencies]
criterion = { version = "0.4", features = ["html_reports"] }
nom = "7.1.3"
pretty_assertions = "1.4.0"
sqlite3-parser = "0.12.0"


[[bench]]
name = "lexer_bench"
harness = false